"""
REAL catalogue scraper template — run this on your own machine, not in a
network-locked sandbox. This sandbox could only reach pypi/npm/github, so
everything else in this project runs on a synthetic catalogue generated by
scripts/gen_catalogue.py. This file is the actual deliverable for "assemble
the catalogue yourself by scraping a public source" — adapt the selectors
to whichever retailer you target and run it where you have normal internet.

Usage:
    pip install requests beautifulsoup4 pillow tqdm
    python scraper_template.py --category sunglasses --max-items 5000

Design notes for whoever runs this for real:
  - Respect robots.txt and the site's terms of service. Rate-limit
    (the sleep below is a floor, not a suggestion) and set a real,
    identifying User-Agent.
  - Cache raw HTML to disk as you go (see `cache_get`) so a crash or a
    selector bug doesn't cost you a full re-crawl — you'll be adapting
    selectors iteratively as you discover the site's actual DOM structure.
  - Pull the highest-resolution product image the page offers (often in
    a data-* attribute or a srcset, not the rendered <img src>) — the
    embedding model will do better with a clean, high-res, front-on shot,
    since that's the "catalogue" side of the domain gap your phone photos
    have to jump at query time.
  - Store item_id, name, category, price, and the image URL/local path
    in metadata.json in the same schema catalogue/metadata.json already
    uses (item_id, file, plus whatever attributes matter for your chosen
    category) so it drops straight into scripts/build_index.py unchanged.
"""
import argparse, hashlib, json, os, time
import requests
from bs4 import BeautifulSoup

USER_AGENT = "catalogue-matcher-research-bot/1.0 (contact: you@example.com)"
MIN_DELAY_SECONDS = 1.5
CACHE_DIR = "scrape_cache"
OUT_IMG_DIR = "catalogue/images"
OUT_META_PATH = "catalogue/metadata.json"


def cache_get(url, session):
    """GETs a URL, caching the raw response to disk so repeated runs (while
    you're still tuning selectors) don't re-hit the network."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    key = hashlib.sha256(url.encode()).hexdigest()
    cache_path = os.path.join(CACHE_DIR, key)
    if os.path.exists(cache_path):
        with open(cache_path, "rb") as f:
            return f.read()
    time.sleep(MIN_DELAY_SECONDS)
    resp = session.get(url, headers={"User-Agent": USER_AGENT}, timeout=20)
    resp.raise_for_status()
    with open(cache_path, "wb") as f:
        f.write(resp.content)
    return resp.content


def discover_listing_pages(base_listing_url, session, max_pages=50):
    """Walk paginated category/listing pages, yielding product page URLs.
    THIS IS THE PART YOU MUST ADAPT: selectors below are illustrative
    placeholders, not tuned to any specific real site."""
    product_urls = []
    for page in range(1, max_pages + 1):
        url = f"{base_listing_url}?page={page}"
        html = cache_get(url, session)
        soup = BeautifulSoup(html, "html.parser")
        # PLACEHOLDER SELECTOR — replace with the target site's actual markup
        links = soup.select("a.product-tile-link, a[data-product-url]")
        if not links:
            break  # no more results, stop paginating
        for a in links:
            href = a.get("href") or a.get("data-product-url")
            if href:
                product_urls.append(href)
        print(f"  listing page {page}: {len(links)} products found "
              f"({len(product_urls)} total so far)")
    return product_urls


def scrape_product_page(url, session):
    """Extracts item_id, name, category, price, and best-quality image URL
    from a single product page. PLACEHOLDER SELECTORS — adapt per site."""
    html = cache_get(url, session)
    soup = BeautifulSoup(html, "html.parser")

    name_el = soup.select_one("h1.product-name, h1[itemprop=name]")
    price_el = soup.select_one(".price, [itemprop=price]")
    img_el = soup.select_one("img.product-main-image, meta[property='og:image']")
    sku_el = soup.select_one("[data-sku], .product-sku")

    image_url = None
    if img_el:
        image_url = (img_el.get("content") or img_el.get("data-src")
                     or img_el.get("srcset", "").split(" ")[0] or img_el.get("src"))

    item_id = None
    if sku_el:
        item_id = sku_el.get("data-sku") or sku_el.text.strip()
    if not item_id:
        item_id = hashlib.sha1(url.encode()).hexdigest()[:12]

    return {
        "item_id": item_id,
        "source_url": url,
        "name": name_el.text.strip() if name_el else None,
        "price": price_el.text.strip() if price_el else None,
        "image_url": image_url,
    }


def download_image(item_id, image_url, session):
    if not image_url:
        return None
    os.makedirs(OUT_IMG_DIR, exist_ok=True)
    ext = ".jpg"
    fname = f"{item_id}{ext}"
    path = os.path.join(OUT_IMG_DIR, fname)
    if os.path.exists(path):
        return fname
    content = cache_get(image_url, session)
    with open(path, "wb") as f:
        f.write(content)
    return fname


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--listing-url", required=True,
                     help="e.g. https://example-retailer.com/sunglasses")
    ap.add_argument("--max-items", type=int, default=5000)
    args = ap.parse_args()

    session = requests.Session()
    print(f"Discovering product pages from {args.listing_url} ...")
    product_urls = discover_listing_pages(args.listing_url, session)
    product_urls = product_urls[:args.max_items]
    print(f"Scraping {len(product_urls)} product pages...")

    metadata = []
    for i, url in enumerate(product_urls):
        try:
            item = scrape_product_page(url, session)
            fname = download_image(item["item_id"], item["image_url"], session)
            if fname:
                item["file"] = fname
                metadata.append(item)
        except Exception as e:
            print(f"  skip {url}: {e}")
        if (i + 1) % 100 == 0:
            print(f"  {i+1}/{len(product_urls)} scraped, {len(metadata)} succeeded")

    with open(OUT_META_PATH, "w") as f:
        json.dump(metadata, f)
    print(f"Done. {len(metadata)} items -> {OUT_META_PATH} / {OUT_IMG_DIR}")


if __name__ == "__main__":
    main()
